package prj.betfair.api.session;

public class SimpleTypes {
  public enum LoginStatusCode {
    SUCCESS, LIMITED_ACCESS, LOGIN_RESTRICTED, FAIL
  }
  public enum LoginErrorCode {
    PENDING_AUTH, SECURITY_QUESTION_WRONG_3X, KYC_SUSPEND, SUSPENDED, STRONG_AUTH_CODE_REQUIRED, DENMARK_MIGRATION_REQUIRED, DANISH_AUTHORIZATION_REQUIRED, SPAIN_MIGRATION_REQUIRED, SPANISH_TERMS_ACCEPTANCE_REQUIRED, ITALY_MIGRATION_REQUIRED, ITALIAN_CONTRACT_ACCEPTANCE_REQUIRED, CHANGE_PASSWORD_REQUIRED, PERSONAL_MESSAGE_REQUIRED, TRADING_MASTER, TRADING_MASTER_SUSPENDED, AGENT_CLIENT_MASTER, AGENT_CLIENT_MASTER_SUSPENDED, INVALID_PIN, INVALID_USERNAME_OR_PASSWORD, PIN_DELETED_ON_FAILED_COUNT_EXCEEDED, UNRECOGNIZED_DEVICE, DUPLICATE_CARDS, ACCOUNT_NOW_LOCKED, ACCOUNT_ALREADY_LOCKED, SECURITY_RESTRICTED_LOCATION, BETTING_RESTRICTED_LOCATION, INVALID_CONNECTIVITY_TO_REGULATOR, INVALID_CONNECTIVITY_TO_REGULATOR_IT, INVALID_CONNECTIVITY_TO_REGULATOR_DK, NOT_AUTHORIZED_BY_REGULATOR, NOT_AUTHORIZED_BY_REGULATOR_DK, NOT_AUTHORIZED_BY_REGULATOR_IT, TELBET_TERMS_CONDITIONS_NA, CLOSED, SELF_EXCLUDED, NOT_AUTHORIZED_FOR_DOMAIN_ES, NOT_AUTHORIZED_FOR_DOMAIN_IT, NOT_AUTHORIZED_FOR_DOMAIN_COM, AUTHORIZED_ONLY_FOR_DOMAIN_ES
  }

}
